# Generated by Django 4.2 on 2023-04-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_alter_bill_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='window',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
