# Generated by Django 4.2 on 2023-04-29 16:08

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_contract_room_room_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentimage',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='document',
        ),
        migrations.RemoveField(
            model_name='billfile',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='room',
        ),
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ForeignKey(blank=True, help_text='The imgages of the apartments.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='core.apartmentimage'),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='core.billfile'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.roomimage'),
        ),
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=models.ImageField(blank=True, help_text='The image of the apartment.', null=True, upload_to='core/images', validators=[core.validators.validate_file_size]),
        ),
    ]
