# Generated by Django 4.2 on 2023-04-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_apartmentimage_apartment_remove_bill_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='created_by',
        ),
    ]
