# Generated by Django 4.2 on 2023-04-29 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_bill_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bills_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
