# Generated by Django 4.2 on 2023-05-04 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_inquiry_from_renter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='from_renter',
        ),
    ]
