# Generated by Django 4.2 on 2023-05-07 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_apartment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='core.apartment'),
        ),
    ]
