# Generated by Django 4.2 on 2023-04-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='bill_documents/'),
        ),
    ]
