# Generated by Django 4.2 on 2023-04-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customuser_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='image',
            new_name='images',
        ),
    ]
