# Generated by Django 4.2 on 2023-05-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='from_renter',
            field=models.BooleanField(default=False),
        ),
    ]
