# Generated by Django 4.2 on 2023-05-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_inquiry_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['city', 'street', 'building_number', 'apartment_number']},
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='address',
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_number',
            field=models.CharField(help_text='The apartment number.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='building_number',
            field=models.CharField(help_text='The building number of the apartment.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.CharField(help_text='The city where the apartment is located.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor',
            field=models.IntegerField(help_text='The floor of the apartment.', null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='street',
            field=models.CharField(help_text='The street where the apartment is located.', max_length=100, null=True),
        ),
    ]
