# Generated by Django 4.2 on 2023-05-07 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_apartment_options_remove_apartment_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='balcony',
            field=models.BooleanField(default=False, help_text='Whether the apartment has a balcony.'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='renter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms_rented', to=settings.AUTH_USER_MODEL),
        ),
    ]
